services:
  app:
    build: .
    container_name: "${CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production