services:
  app:
    build: .
    container_name: tcsd_control_api
    restart: unless-stopped
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production